### PR TITLE
Added custom bootstrap based theme

### PR DESCRIPTION
**Pull request by kaypro4**
Closes issue #16.  My first pull request!  Hope it works...

### CODE REVIEW

**Comment by kaypro4** [comment]
@fureigh can you see if I did this right?

**Comment by fureigh** [comment]
Looks good to me! :+1:

**Comment by fureigh** [comment]
@kaypro4, I'm inclined to delete extra branches once they're merged in, to keep things tidy. Cool with you?

**Comment by kaypro4** [comment]
I'm cool with that too.  Just deleted this one.

**Pull request merged**
